
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urls
    ports:
      - "3306:3306"
    volumes:
      - /home/armaan/github/shortURL/urldb:/var/lib/mysql

  web:
    build: ./web
    image: urlimg:1.0
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  {}
